# Generated by Django 4.1.7 on 2023-02-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[(1, 'Home Security'), (2, 'Fire Safety'), (3, 'Water Supply'), (4, 'Electricity Supply'), (5, 'Video Supervision'), (6, 'Climatization'), (7, 'Lighting'), (8, 'Meters'), (9, 'Alert'), (10, 'Power')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Controller'), (2, 'Sensor'), (3, 'Object')], default=1)),
                ('interface', models.IntegerField(choices=[(1, 'Wi Fi'), (2, 'Ethernet'), (3, 'Rs 485')], default=1)),
                ('ip', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My home', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My room', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='devices',
            field=models.ManyToManyField(through='smart_home.RoomDevice', to='smart_home.device'),
        ),
        migrations.AddField(
            model_name='room',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.home'),
        ),
        migrations.CreateModel(
            name='HomeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.home')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='devices',
            field=models.ManyToManyField(through='smart_home.HomeDevice', to='smart_home.device'),
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'home')},
        ),
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('name', 'user')},
        ),
    ]
