# Generated by Django 4.1.7 on 2023-03-05 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('device_category', models.IntegerField(choices=[(1, 'Home Security'), (2, 'Fire Safety'), (3, 'Water Supply'), (4, 'Electricity Supply'), (5, 'Video Supervision'), (6, 'Climatization'), (7, 'Lighting'), (8, 'Meters'), (9, 'Alert'), (10, 'Power')], default=1)),
                ('device_type', models.IntegerField(choices=[(1, 'Controller'), (2, 'Sensor'), (3, 'Executive Object')], default=1)),
                ('interface', models.IntegerField(choices=[(1, 'Wi Fi'), (2, 'Ethernet'), (3, 'Rs 485')], default=1)),
                ('ip', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My home', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My room', max_length=50)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.home')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'home')},
            },
        ),
        migrations.CreateModel(
            name='DeviceProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Property', max_length=50)),
                ('input', models.CharField(blank=True, default=None, max_length=50)),
                ('output', models.CharField(blank=True, default=None, max_length=50)),
                ('min_value', models.IntegerField(blank=True, default=0)),
                ('max_value', models.IntegerField(blank=True, default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='smart_home.room')),
            ],
            options={
                'ordering': ['note'],
                'unique_together': {('device', 'note')},
            },
        ),
        migrations.CreateModel(
            name='HomeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
                ('home', models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='smart_home.home')),
            ],
            options={
                'ordering': ['note'],
                'unique_together': {('device', 'note')},
            },
        ),
    ]
