# Generated by Django 4.1.7 on 2023-03-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceproperties',
            unique_together={('device', 'name')},
        ),
    ]
