# Generated by Django 4.1.7 on 2023-03-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='category',
            new_name='device_category',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'Controller'), (2, 'Sensor'), (3, 'Executive Object')], default=1),
        ),
    ]
