# Generated by Django 4.1.7 on 2023-03-01 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_home', '0002_rename_category_device_device_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'home')},
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('device', 'note')},
        ),
        migrations.AddField(
            model_name='userdevice',
            name='home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='smart_home.home'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='smart_home.room'),
        ),
        migrations.RemoveField(
            model_name='home',
            name='user_device',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_device',
        ),
    ]
