# Generated by Django 4.1.7 on 2023-03-01 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0003_alter_home_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='Usage...', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
                ('home', models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='smart_home.home')),
            ],
            options={
                'ordering': ['device'],
                'unique_together': {('device', 'note')},
            },
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='Usage...', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.device')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.fields.NOT_PROVIDED, to='smart_home.room')),
            ],
            options={
                'ordering': ['device'],
                'unique_together': {('device', 'note')},
            },
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
